config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  resources :events do 
    resources :event_sessions do
      get :view_attendees
      resources :session_bookings, only: [:new, :create, :destroy]	
    end
  end
  resources :categories
  namespace :session_bookings do
    get :approvals 
    patch :approve_or_reject
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      can :read, Event
    elsif user.role? "admin"
      can :manage, :all
    elsif user.role? "host" 
      can [:update, :destroy], Event do |event|
        event.try(:user) == user
      end
      can [:create, :read], Event
      can [:read, :view_attendees], EventSession
      can :read, SessionBooking
    elsif user.role? "attendee"
      can :read, Event
      can :read, EventSession
      can :create, SessionBooking
    end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_sessions, dependent: :destroy
  belongs_to :user
  
  validates :name, :start_datetime, :end_datetime, :image, :address, presence: true
  before_create :check_date

  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  private 

  def check_date
    if self.start_datetime >= self.end_datetime
      errors.add(:start_datetime," is invalid!")	
    end
  end	
end

app/models/event_session.rb
class EventSession < ApplicationRecord
  belongs_to :event
  has_many :session_bookings

  scope :host_sessions, -> (user_id){ where(host_id: user_id)}

  validates :name, :start_datetime, :end_datetime, :host_id, presence: true

  def is_enrolled?(user)
  	SessionBooking.where(event_session_id: self.id, user_id: user.id).present?
  end
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :role	
end

app/models/role.rb
class Role < ApplicationRecord
  validates :name, uniqueness: true

  has_many :permissions
  has_many :users, through: :permissions
end

app/models/session_booking.rb
class SessionBooking < ApplicationRecord
  belongs_to :user
  belongs_to :event_session
  after_create :update_status

  STATUSES = {approved: "Approved", rejected: "Rejected", pending: "Pending"}.freeze
  
  scope :requests, ->{ where(status: STATUSES[:pending])}


  def update_status
  	self.update_attribute(:status, STATUSES[:pending])
  end

  def host
  	User.find(self.host_id)
  end
  
  def is_approved?
  	self.status == STATUSES[:approved]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_uniqueness_of :email

  has_many :permissions
  has_many :roles, through: :permissions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_user_role

  def role?(role)
  	self.roles.pluck(:name).include? role
  end

  def self.hosts
  	User.all.collect { | user | [user.name, user.id] if user.role? "host"}.compact
  end

  def is_host?
  	self.role? "host"
  end  
  
  private

  def assign_user_role
  	Permission.create(user_id: self.id, role_id: Role.last.id)
  end
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
	events_path
  end

  # rescue_from CanCan::AccessDenied do 
  # 	redirect_to root_path, alert: "You are not authorized to access this section!"
  # end
end

app/controllers/event_sessions_controller.rb
class EventSessionsController < ApplicationController
  before_action :set_event, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_event_session, only: [:edit, :update, :destroy]
  def index
  end

  def new
    @event_session = @event.event_sessions.new
  end

  def create
    @event_session = @event.event_sessions.new(event_session_params)
    if @event_session.save
      flash[:success] = "Session has been created successfully"
      redirect_to event_path(@event.id)
    else
      flash[:error] = "Invalid form"
      render "new"
    end
  end

  def edit
  end

  def update
    if @event_session.update(event_session_params)
      flash[:success] = "Session has been created successfully"
      redirect_to event_path(@event.id)
    else
      flash[:error] = "Invalid form"
    end
  end

  def destroy
    @event_session.destroy
    redirect_to event_path(@event), notice: "Deleted successfully!" 
  end

  def view_attendees
    @attendees = SessionBooking.where(event_session_id: params[:event_session_id], host_id: current_user.id)
  end


  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_event_session
    @event_session = EventSession.find(params[:id])
  end

  def event_session_params
    params.require(:event_session).permit(:name, :description, :start_datetime, :end_datetime, :event_id, :host_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    if @event.save
      redirect_to events_path, notice: "Successfully added!"
    else
      render "new"
    end
  end

  def show
    @event = Event.find(params[:id])
    @event_sessions = (current_user.is_host?) ? EventSession.host_sessions(current_user.id) : @event.event_sessions 
    @session_booking = SessionBooking.new
    @session_bookings = SessionBooking.where(host_id: current_user.id)
  end

  def edit
  end

  def update
    if @event.update(event_params)
      flash[:success] = "Event has been updated Successfully."
      redirect_to events_path
    else
      render "edit"
    end
  end

  def destroy
    @event.destroy
    flash[:success] = "Event has been deleted Successfully"
    redirect_to events_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :image, :description, :venue_id, :city_id, :start_datetime, :end_datetime, :entry_fee, :status, :avatar, :address)
  end
end

app/controllers/session_bookings_controller.rb
class SessionBookingsController < ApplicationController
  before_action :set_session_booking, only: [:create]

  def new
    @session_booking = SessionBooking.new
  end

  def create
    @session_booking = SessionBooking.create(event_session_id: params[:event_session_id], host_id: @event_session.host_id, user_id: current_user.id)
    redirect_to event_path(params[:event_id])
  end

  def edit
  end

  def show
  end

  def destroy
  end

  def approvals
    @session_bookings = SessionBooking.all
  end

  def approve_or_reject
    @session_booking = SessionBooking.find(params[:id])
    @session_booking.update_column(:status, params[:commit] + "d")
    redirect_to session_bookings_approvals_path
  end

  private

  def set_session_booking
    @event_session = EventSession.find(params[:event_session_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_bookings_helper.rb
module EventBookingsHelper
end

app/helpers/event_sessions_helper.rb
module EventSessionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/session_bookings_helper.rb
module SessionBookingsHelper
end

app/views/event_sessions/_attendees.html.erb
<div class="modal" id="myModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">My Attendees (<%= @attendees.count %>)</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>

			<div class="modal-body">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>#</th>
							<th>SessionName</th>
							<th>Attendee Name</th>
							<th>Email</th>
						</tr>
					</thead>
					<tbody>
						<% unless @attendees.blank? %>
						<% @attendees.each_with_index do |session, i| %>
						<tr>
							<td><%= i+1 %></td>
							<td><%= session.event_session.name %></td>
							<td><%= session.user.name %></td>
							<td><%= session.user.email %></td>
						</tr>
						<%end %>
						<% else%>
						  <tr>
						  	No Records.
						  </tr>
						<% end%>
					</tbody>
				</table>
			</div>

			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
			</div>

		</div>
	</div>
</div>

app/views/event_sessions/_form.html.erb
<%= form_for @event_session, url: @event_session.new_record? ? event_event_sessions_path(@event) : event_event_session_path(@event), html: {class: "form-horizontal"} do |f| %>
<% if @event_session.errors.any? %>
<div class="alert alert-danger">
	<h3>These errors prohibited the form from being created:</h3>
	<ul>
		<% @event_session.errors.full_messages.each do |msg| %>
		<li><%= msg%></li>
		<% end %>
	</ul>			
</div>	
<% end %>

<div class="form-group">
	<%= f.label :name %>*
	<%= f.text_field :name, class: "form-control" %>		
</div>
<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, class: "form-control" %> 		
</div>
<div class="form-group">
		<%= f.label "Starting at" %>*
	<%= f.text_field :start_datetime, id: "startDatetime", class: "form-control" %> 
	</div>

	<div class="form-group">
		<%= f.label "Ending at" %>*
	<%= f.text_field :end_datetime, id: "endDatetime", class: "form-control" %> 
	</div>

	<div class="form-group">
		<%= f.label "Host" %>*
		<%= f.select :host_id, options_for_select(User.hosts), {prompt: "Please select"}, class: "form-control"%>
	</div>
	<%= f.submit "Submit", class: "btn btn-success"%>

<% end %>

app/views/event_sessions/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
			<h1 class="display-4 py-2 text-truncate">Edit Session</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/event_sessions/index.html.erb
<h1>EventSessions#index</h1>
<p>Find me in app/views/event_sessions/index.html.erb</p>

app/views/event_sessions/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
			<h1 class="display-4 py-2 text-truncate">Add Session</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/event_sessions/show.html.erb
<h1>EventSessions#show</h1>
<p>Find me in app/views/event_sessions/show.html.erb</p>

app/views/event_sessions/view_attendees.js.erb
$(".attendees").html("<%= escape_javascript render 'attendees'%>")
$("#myModal").modal()

app/views/events/_form.html.erb
<%= form_for @event, html: {class: "form-horizontal"} do |f| %>
	<% if @event.errors.any? %>
		<div class="alert alert-danger">
			<h3>These errors prohibited the form from being created:</h3>
			<ul>
				<% @event.errors.full_messages.each do |msg| %>
				<li><%= msg%></li>
				<% end %>
			</ul>			
		</div>	
	<% end %>
	
	<div class="form-group">
			<%= f.label :name %>*
	<%= f.text_field :name, class: "form-control" %>		
	</div>

	
	<div class="form-group">
			<%= f.label :image %>*
	<%= f.file_field :image, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :description %>
	<%= f.text_area :description, class: "form-control" %> 		
	</div>

	<div class="form-group">
		<%= f.label :address %>*
	<%= f.text_area :address, class: "form-control" %> 		
	</div>

	<div class="form-group">
		<%= f.label "Starting at" %>*
	<%= f.text_field :start_datetime, id: "startDatetime", class: "form-control" %> 
	</div>

	<div class="form-group">
		<%= f.label "Ending at" %>*
	<%= f.text_field :end_datetime, id: "endDatetime", class: "form-control" %> 
	</div>
	

	<div class="form-group">
		<%= f.label :entry_fee %>
	<%= f.number_field :entry_fee, class: "form-control" %> 
	</div>

	<div class="form-group">
		<%= f.label :status %>
	<%= f.select :status, ["New", "On-going", "Over"], {}, class: "form-control" %> 	
	</div>

	<%= f.submit "Submit", class: "btn btn-success"%>
</div>
<% end %>

app/views/events/_sessions.html.erb
<h2>Sessions</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Start Time</th>
      <th>End Time</th>
      <% if (can? :update, EventSession.new) || (can? :create, SessionBooking.new) || (can? :view_attendees, EventSession.new)%>
      <th>Actions</th>
      <% end %>  
    </tr>
  </thead>
  <tbody>
    <% @event_sessions.each_with_index do |session, i| %>
    <tr>
      <td><%= i+1 %></td>
      <td><%= session.name %></td>
      <td><%= session.description %></td>
      <td><%= session.start_datetime.to_time.strftime('%B %e at %l:%M %p') %></td>
      <td><%= session.end_datetime.to_time.strftime('%B %e at %l:%M %p') %></td>
      <% if (can? :update, EventSession.new) || (can? :create, SessionBooking.new) || (can? :view_attendees, EventSession.new)%>
      <td>
        <p>
        <% if can? :update, EventSession.new %>
          <%= link_to edit_event_event_session_path(@event.id, session.id) do %>
             <i class="fa fa-pencil"></i>
              <%end%>
              <%= link_to event_event_session_path(@event.id, session.id), method: :delete, class: "ml-2" do %>
             <i class="fa fa-trash"></i>
              <%end%>
        <%end%>
        <% if can? :view_attendees, EventSession.new %>
        <%= link_to event_event_session_view_attendees_path(@event.id, session.id), class: "ml-2", remote: true do %>
             <i class="fa fa-eye"></i>
              <%end%>
        <% end %>
        <% if can? :create, SessionBooking.new %>
        <%= form_for([@event,session, @session_booking]) do |f|  %>
        <%= f.submit "Enroll" , class: "btn btn-danger", disabled: session.is_enrolled?(current_user)%>
        <% end %>
        <% end %>	
        </p>
        
      </td>
      <% end %>	
    </tr>
    <%end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
			<h1 class="display-4 py-2 text-truncate">Edit Event</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<% if can? :create, EventSession.new %>
  <div class="card bg-light text-dark mt-2">
    <div class="card-body text-center">
      <h3><%= link_to "Click here", new_event_path %>  to create an Event!</h3>
    </div>
  </div>
<% end %>
<div class="row mt-2 p-0">
  <% @events.each do |event|%>
  <div class="col-12 col-sm-6 col-md-4 col-lg-3">
    <div class="card">
      <%= link_to image_tag(event.image.url, height: "150px", width: "100%"), event_path(event) %>
      <div class="card-padding">
        <!-- Event Header -->
        <div class="row m-2">
          <h5 class="text-center"><%= link_to "#{event.name}", event_path(event) %></h5>
        </div>
        <!-- Event Control Panel -->
        <div class="row p-0">
          <div class="col-md-8">
            <p class="ml-2 text-primary">Entry fee: <%= event.entry_fee %></p>
          </div>
          <div class="col-md-4">
            <p class="text-center">
              <% if can? :create, EventSession.new %>
              <%= link_to edit_event_path(event) do %>
             <i class="fa fa-pencil"></i>
              <%end%>
              <%= link_to event_path(event), method: :delete, class: "ml-2", data: {confirm: "Are you sure?"} do %>
              <span class="fa fa-trash"></span>
              <%end%>	
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-md-6 ">
            <p class="m-2 well well-sm"> <small><%= event.end_datetime.strftime("%d %b %Y") %></small></p>
          </div>
          <div class="col-sm-6 col-md-6" style="margin-top:2px">
            <p class="text-center"><a href="/events/<%= "#{event.id}" %>" class="btn btn-danger" role="button" style="border: none; color: white;">View Event</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/events/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4">
			<h1 class="display-4 py-2 text-truncate">Create Event</h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="page-header">
    <ol class="breadcrumb mt-2">
      <li><%= link_to "Events", events_path, class: "m-1" %></li>
      /
      <li class="active ml-1"><%= link_to @event.name, event_path(@event) %></li>
    </ol>
  </div>
  <div class="row">
    <div class="col-md-7 p-0" >
      <h2><%= @event.name %></h2>
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <%= image_tag(@event.image.url, height: "200px", width: "100%" ) if @event.image%>
            <div class="carousel-caption">
              Image 1
            </div>
          </div>
        </div>
      </div>
      <!-- carousel ends here -->		
    </div>
    <div class="col-md-5 mt-5">
      <b><%= @event.description %> </b><br/>
      <b>Starting from :</b> <%= @event.start_datetime.strftime("%d %B %Y - %I:%M %P ") %> <br/>
      <b>Ending at :</b> <%= @event.end_datetime.strftime("%d %B %Y - %I:%M %P ") %><br/>
      <% if can? :create, EventSession.new %>
      <%= link_to "Add Session", new_event_event_session_path(@event.id), class: "btn btn-danger mt-3"%>
      <% end %>
    </div>
  </div>

  <div class="row mt-5">
    <% if can? :read, EventSession.new %>
    <%= render 'sessions'%>
    <% end %>
  </div>
  <div class="attendees">
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small teal border bg-light pt-5">
  <div class="container-fluid text-center ">
    <div class="row">
      <div class="col-md-4 mt-md-0 mt-3">
        <h5 class="text-uppercase font-weight-bold">Admin</h5>
        <p>admin@event.com</p>
        <p>admin@123</p>
      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-4 mb-md-0 mb-3">
        <h5 class="text-uppercase font-weight-bold">Host</h5>
        <p>host@event.com</p>
        <p>host@123</p>
      </div>
      <div class="col-md-4 mb-md-0 mb-3">
        <h5 class="text-uppercase font-weight-bold">Attendee</h5>
        <p>attendee@event.com</p>
        <p>atte@123</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventManagement</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #fd614a">
    <a href="#" class="navbar-brand"><h4 class="text-default">Event Management</h4></a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <div class="navbar-nav ml-auto">
        <%= link_to "Home", root_path, class: "nav-item nav-link active" %>
        <% if can? :approvals, SessionBooking.new%>
        <%= link_to session_bookings_approvals_path, class: "nav-item nav-link active" do %>
        Approvals<b>(<%= SessionBooking.requests.size %>)</b>
        <% end %>  
        <% end %> 
        <% if user_signed_in? %>
        <a href="#" class="nav-item nav-link active"><%= current_user.name %></a>
        <%= link_to "Edit Account", edit_user_registration_path, class: "nav-item nav-link active" %>
        <%= link_to "Logout", destroy_user_session_path, class: "nav-item nav-link active", method: :delete %>
        <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-item nav-link active" %>
        <%= link_to "Register", new_user_registration_path, class: "nav-item nav-link active" %>
        <% end %>  
      </div>
    </div>
  </nav>
  <div class="container-fluid  justify-content-center align-items-center h-100">
    <% if flash[:success].present? %>
      <div class="alert alert-success mt-2">
        <strong><%= flash[:success]%></strong>
      </div>
    <% end%>
    <% if flash[:error].present? %>
      <div class="alert alert-danger">
        <strong><%= flash[:error]%></strong>
      </div>
    <% end%>
    <% flash.clear%>
    <%= yield %>
  </div>    
</body>
</html>

app/views/session_bookings/_attendees.html.erb
	<div class="row">
		<div class=" ">
			<% if can? :read, SessionBooking.new %>
			<h3>My Sessions</h3>

			<table class="table table-bordered">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Description</th>
						<th>Start Time</th>
						<th>End Time</th>
					</tr>
				</thead>
				<tbody>
					<% @session_bookings.each_with_index do |session, i| %>
					<tr>
						<td><%= i+1 %></td>
						<td><%= session.event_session.name %></td>
						<td><%= session.event_session.description %></td>
						<td><%= session.event_session.start_datetime.to_time.strftime('%B %e at %l:%M %p') %></td>
						<td><%= session.event_session.end_datetime.to_time.strftime('%B %e at %l:%M %p') %></td>
					</tr>
					<%end %>
				</tbody>
			</table>
			<% end %>
		</div>
	</div>

app/views/session_bookings/approvals.html.erb
<div class="row">
	<h3>Participation Requests</h3>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Description</th>
				<th>Start Time</th>
				<th>End Time</th>
				<th>Host</th>
				<th>Status</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @session_bookings.each_with_index do |session, i| %>
			<tr>
				<td><%= i+1 %></td>
				<td><%= session.event_session.name %></td>
				<td><%= session.event_session.description %></td>
				<td><%= session.event_session.start_datetime.to_time.strftime('%B %e at %l:%M %p') %></td>
				<td><%= session.event_session.end_datetime.to_time.strftime('%B %e at %l:%M %p') %></td>
				<td><%= session.host.name %></td>
				<td><%= session.status %></td>
				<td>
					<%= form_for([session], url: session_bookings_approve_or_reject_path(id: session.id)) do |f|  %>
					<%= f.submit "#{session.is_approved? ? 'Reject' : 'Approve'}" , class: "btn btn-info"%>
					<% end %>	
				</td>
			</tr>
			<%end %>
		</tbody>
	</table>
</div>

app/views/session_bookings/edit.html.erb
<h1>SessionBookings#edit</h1>
<p>Find me in app/views/session_bookings/edit.html.erb</p>

app/views/session_bookings/index.html.erb
<h1>SessionBookings#index</h1>
<p>Find me in app/views/session_bookings/index.html.erb</p>

app/views/session_bookings/new.html.erb
<h1>SessionBookings#new</h1>
<p>Find me in app/views/session_bookings/new.html.erb</p>